server:
  port:8081

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange:
      producer: ex.producer.aula
    routing-key:
      producer: rk.producer.aula
    deadletter:
      producer: dl.producer.aula